title: CCAMLR Science Toolbox
logo: /assets/img/Logo.png
description: www.ccamlr.org
show_downloads: true
kramdown:
  math_engine: mathjax
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme