title: CCAMLR Science Toolbox
logo: /assets/img/Logo.png
description: [www.ccamlr.org](https://www.ccamlr.org/)
show_downloads: true
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme